name: Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run tests
        run: swift test

  build:
    strategy:
      fail-fast: false
      matrix:
        xcode-version: ["16.4"]
        package-scheme:
          - name: rootful
            value: ""
          - name: rootless
            value: rootless
          - name: roothide
            value: roothide

    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          path: orion

      - name: Set Up Dependencies
        run: |
          brew install ldid make fakeroot
          echo "PATH=/usr/local/opt/make/libexec/gnubin:${PATH}" >> "${GITHUB_ENV}"

      - name: Install Theos
        uses: waruhachi/theos-action@v2.6.3
        with:
          theos-src: waruhachi/theos
          theos-branch: main
          sdks-src: waruhachi/sdks
          sdks-branch: main

      - name: Build ${{ matrix.package-scheme.name }}
        working-directory: orion
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer
          PACKAGE_SCHEME: ${{ matrix.package-scheme.value }}
        run: |
          make clean package \
            THEOS_PACKAGE_SCHEME="${PACKAGE_SCHEME}"